### PR TITLE
support arbitrary repository/kustomization root

### PR DESCRIPTION
**Pull request by torfjor**

### CODE REVIEW

**Comment by mjenssen** [comment]
LGTM, but I'm not quite sure on what the values are supposed to be. Could you update `README.md` as well (especially the example)?

**Comment by torfjor** [comment]
I was thinking that instead of creating a matrix for each overlay to update, a consuming repository could specify:
```yaml
inputs:
  push_overlays: overlay-1 overlay-2 overlay-3
  release_overlays: overlay-4 overlay-5 overlay-6
```
That way we only get one commit and don't have to deal with failed push because the copy in the action has fallen behind another member of the matrix.

**Comment by mjenssen** [comment]
But each overlay is supposed to be prefixed with `overlay/`? Like this:

```yaml
inputs:
  push_overlays: overlays/tenant1-staging overlays/tenant2-staging
  release_overlays: overlays/tenant1-prod overlays/tenant2-prod
```

**Comment by torfjor** [comment]
> But each overlay is supposed to be prefixed with `overlay/`? Like this:
> 
> 
> 
> ```yaml
> 
> inputs:
> 
>   push_overlays: overlays/tenant1-staging overlays/tenant2-staging
> 
>   release_overlays: overlays/tenant1-prod overlays/tenant2-prod
> 
> ```
> 
> 

Nope. That's an oversight 😂

**Review by mjenssen — APPROVED** [review]
LGTM, but these must be fixed:

- [ ] Add default overlays
- [ ] Update README.md

**Pull request merged**
